#!/usr/bin/python3

import socket
import sys, getopt

def parse_args(argv):
    portid = ''
    outputfile = ''
    pwdfile = ''
    try:
        opts, args = getopt.getopt(argv,"p:o:f:",[])
    except getopt.GetoptError:
        print('./kdc -p 12345 -o out.txt -f pwd.txt')
        sys.exit(2)
    for opt, arg in opts:
        if opt == "-p":
            portid = arg
        elif opt == "-o":
            outputfile = arg
        elif opt == "-f":
            pwdfile = arg
    return (portid, outputfile , pwdfile)

def main():
    # setting up a listening socket for kdc server.
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as serversocket:
        serversocket.bind(('localhost', int(portid)))
        serversocket.listen(5)
        print(f"Listening on port {int(portid)}")
        print("Waiting for connection from client.......")
        # client_connection_socket is different from serversocket. 
        # This new socket obejct is used for communication between client and server
        (client_connection_socket, address) = serversocket.accept()
        with client_connection_socket:
            print('Connected by', address)
            while True:
                data = client_connection_socket.recv(1024)
                if not data:
                    break
                client_connection_socket.sendall(data)

if __name__ == "__main__":
   portid, outputfile, pwdfile = parse_args(sys.argv[1:])
   main()